# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e127ccbf0a07ca561dd31dda9cb12e3b6cab9274a6be6234328f6e7336018d3e685984aaa74d21b9f5d649d27be81a438ca4771b4d89e8788eac1cc73cefc00a

test:
  secret_key_base: 0a8cc189f20018e01b3fcf42f989aca6769024ace72bed932f34fcd43f34ad2992027f33c67e31b81488270f362fdee39403b8c4f4dd800c7b5325b1d6f9ca51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
